### PR TITLE
Fix #180 by enhancing static type analysis

### LINKED ISSUE #180: Lint crashes when assigning Union{} as tuple
```
julia> lintstr("""
       x, y = error()
       """)
ERROR: type BottomType has no field parameters
Stacktrace:
 [1] #lintassignment#17(::Bool, ::Bool, ::Bool, ::Bool, ::Function, ::Expr, ::Symbol, ::Lint.LintContext) at /home/fengyang/.julia/v0.6/Lint/src/variables.jl:247
 [2] lintexpr(::Expr, ::Lint.LintContext) at /home/fengyang/.julia/v0.6/Lint/src/Lint.jl:205
 [3] lintstr(::String, ::Lint.LintContext, ::Int64) at /home/fengyang/.julia/v0.6/Lint/src/Lint.jl:164
 [4] lintstr(::String) at /home/fengyang/.julia/v0.6/Lint/src/Lint.jl:137
```

### LINKED ISSUE #182: E418 issues
```
julia> lintstr("    a, = (1,2,3)")
0-element Array{Lint.LintMessage,1}

julia> lintstr("    a,b = (1,2,3)")
1-element Array{Lint.LintMessage,1}:
 none:1 E418 Tuple{Int64,Int64,Int64}: RHS is a tuple, 2 of 3 variables used

julia> lintstr("    a,b,c = (1,2,3)")
0-element Array{Lint.LintMessage,1}

julia> lintstr("    a,b,c,d = (1,2,3)")
1-element Array{Lint.LintMessage,1}:
 none:1 E418 Tuple{Int64,Int64,Int64}: RHS is a tuple, 4 of 3 variables used
```

Case 1: this is a likely problem and we should warn, see below.
Case 2: this is a likely problem and we should warn, but E418 is probably too severe. This code runs perfectly well; all the numbers past the first two are discarded.
Case 3: this is fine
Case 4: this is fine

### PR DESCRIPTION
**Pull request by TotalVerb**
Instead of using `parameters` which doesn't always work, we fall back to inference to determine the nth element type in static type analysis. Depends on several other PRs to be merged first.

Fixes #180 
Fixes #182 

Introduces E539 to fix #180 and W546 to fix #182.

### CODE REVIEW

**Comment by TeroFrondelius** [comment]
What is needed to get this merged?

**Comment by TotalVerb** [comment]
The tests need to pass. I'll get around to it tomorrow.

**Comment by TotalVerb** [comment]
This depends on #179, and currently, #179 hangs on master for what I suspect is related to the lint server. I believe that hang wasn't detected by CI because it failed before the server code was tested. I'll have to investigate that first.

**Comment by TotalVerb** [comment]
Now that #179 is in, I'll rebase this tonight. Hopefully it should be ready soon.

**Comment by TotalVerb** [comment]
@TeroFrondelius @Michael-Klassen If you'd like to look this over, this is now ready for review. Otherwise, I'll merge it by March 17.

**Pull request merged**
