### PR TITLE
RFC Refactor

### PR DESCRIPTION
**Pull request by Michael-Klassen**
Change the error codes from an int (0-3) to a symbol uniquely identifying the message in the universe of messages and it's error level. The codes now start with a letter for the severity `E`:`ERROR`, `W`:`WARN` or `I`:`INFO` and then has 3 numbers identifying the error. A list of all the errors that exist is in the "errorcodes.md" file. Message output is of the following form: `filename.jl:Line CODE variable: message`.

Add support for global variables defined later.

Move message methods to their own file.

Fix Package evaluator badge.

Refactor docs for read the docs

Fix several bugs I came across while working on this.

Full list of changes below:

Message Changes
===============
 * Remove redundant `FATAL` error level
 * Change message `level` to be a `Symbol`
 * Add error codes (issue #106)
 * Reformat message string
 * Move message methods to their own file

Bugs Fixes (exceptions)
==========
 * `1=1`
 * `function () end`
 * `function foo end`
 * `function f(x::ANY...) x[1] end` (issue #109)
 * dictionary: `d[]`
 * string: `s[]`
 * `macro () end`
 * `@lintpragma()`
 * `a = begin end`
 * `d = Dict{int, int}()`

Bug Fixes (features)
=========
 * Fix use of undeclared symbol when function definition uses global variable defined later (issue #86)
 * Add support for using globals declared within the package

General Changes
===============
 * Change `INFO` message to print as `bold` to make it more readable
 * Added test for incomplete expressions
 * Fix deprecated warnings
 * Make whitespace more consistent: The original code used mostly `( foo )` format but later contributions use `(foo)` format. Base julia also uses `(foo)` format. I changed the code to consistently use `(foo)` format.
 * Refactor LintIgnore
 * Update documentation
 * Fix package evaluator badge
 * Refactor docs for read the docs
 * Fix error wordings: Many of the error messages have the relevant variable unnecessarily repeated in the message
 * Fix linting of macro with no args

TODO
====
 * How should base julia be linted?

### CODE REVIEW

**Comment by TotalVerb** [comment]
+1. Only thing is, I don't know if I like this approach to two-pass linting. It's a bit ad-hoc. I'd like to see a more flexible system.

**Comment by Michael-Klassen** [comment]
@TotalVerb In my opinion it is much easier to just filter the messages as they resolve then actually parsing the files 2 times. I agree that it does feel a bit ad-hoc to filter the messages every time we come across a new global but because there are relatively few messages and globals, I would argue that it is also the faster approach. I agree a more flexible system would be nice, this PR is already getting pretty big and that can be done in a future PR. I aim to close #86 not necessarily #12.

**Comment by Michael-Klassen** [comment]
I updated the documentation. Here is a link to what it will look like on read the docs: https://lintjl.readthedocs.org/en/mdk-development/

**Comment by tonyhffong** [comment]
nice!!!

**Comment by tonyhffong** [comment]
@Michael-Klassen I agree with your 2-pass comment. Given the size of this PR, let's go ahead with this and open a separate debate on the merits of a 2-pass vs post-lint message filter.

**Comment by tonyhffong** [comment]
@Michael-Klassen also, this is a very substantial PR. Thank you! Would you be interested to be a collaborator so you can have full merge right?

**Comment by Michael-Klassen** [comment]
@tonyhffong I find this linter incredibly useful and I would definitely be interested in being a collaborator.

**Comment by TotalVerb** [comment]
I think this branch should be merged soon, or at least no new commits should be added. This PR is incredibly broad in scope already.

**Comment by Michael-Klassen** [comment]
@TotalVerb I agree.

**Comment by tonyhffong** [comment]
Done. And I added you as a collaborator. Thanks and welcome aboard! @Michael-Klassen

**Pull request merged**
